--Sakura's Archetype/Set Codes

--This exists for the same reason as the official version; easier to type this stuff rather than HEX CODE every time. especially if the need to change the archetype code arises. Will be listed alphabetically, with any sub/related archetypes kept together.

--Archetypes
SET_AGM				=   0x7DF
SET_AURA_BEAST			=   0x7E5
SET_BAOFENG_DRAGON		=   0x7D8
SET_BLAZEFUR_ATHLETE			=   0x7D7
SET_BUNNY					=   0x7D0
SET_CHERRYRABBIT				=   0x7DB
SET_DIVER					=   0x4af
SET_DIVERDEER				=   0x14af
SET_DIVEREQUINE		=   0x24af
SET_DIVERVULPINE				=   0x44af
SET_DREAMLIGHT			=   0x5F7
SET_DREAMSTAR				=   0x5F8
SET_ECLIPSEDREAM				=   0x5F9
SET_ERPETAMETENSAR		=   0x7C5
SET_FLASH_BLOSSOM_REINDEER  =   0x4c8
SET_FLASH_RESISTANCE_REINDEER   =   0x4CA
SET_FLYER					=   0x4c9
SET_FLASH_FLYER		=   0x24c9
SET_SNOW_FLYER			=   0x14c9
SET_HAZMAT_ANIMAL			=   0x43a
SET_LIFESTREAM			=   0x7DA
SET_MAGICALGIRL		=   0x5F3
SET_NAVALFUR					=   0x7BD
SET_OLYMPIDRAGON				=   0x7E8
SET_PHOENIXGUARD				=   0x652
SET_PONY						=   0x439
SET_SCUBA_PONY			=   0x2439
SET_SUPERSTAR_PONY		=   0x1439
SET_PRONGSTORM			=   0x7D1
SET_PSYCHIC_DRAGON		=   0x5F1
SET_PSYCHIC_HERO				=   0x5F2
SET_RADIANT_DRAGON_REINDEER  =   0x96C
SET_RESISTANCEDRAGON			=   0x7DC
SET_RESISTANCE_AVATAR		=   0x7E1
SET_WISPON				=   0x7E2
SET_RIDER_DEER			=   0x5F4
SET_ROCKETBLOSSOM_DEER	=   0x7AE
SET_SAPPHIREDREAM			=   0x7DE
SET_SG					=   0x7D5
SET_SG_CATCHER			=   0x17D5
SET_SG_MORPH					=   0x37D5
SET_SG_TRANSFORMATION		=   0x27D5
SET_SG_UKKI			=   0x47D5
SET_SKATEBOARD_DRAGON		=   0x5f0
SET_SKYFURRY					=   0x7E0
SET_SKYSTORM_MECHA		=   0x7C7
SET_SNOWSTORM_RABBIT			=   0x7E7
SET_SNOWSTORM_REINDEER	=   0x9D0
SET_STARBLOSSOM_REINDEER		=   0x4CB
SET_STARRY_SKYSTORM_RABBIT  =   0x7F3
SET_STARRY_SNOW_BLOSSOM_REINDEER =  0xA34
SET_SUNBEAST					=   0x640
SET_TECHZODIAC			=   0x7D9
SET_TRONZOO			=   0x7C8
SET_VEEVEE				=   0x7D2
SET_ZPD				=   0x4b0
SET_ZPDELTA			=   0x4ad
SET_ZPDELTA_BEAST			=   0x24ad
SET_ZPDELTA_RANGER		=   0x14ad

-- Unused Codes (may be subject to removal or change as needed)
 
	--0x642  RI-ON
	--0x643  ELECTRIC FIELD
	--0x644  FANTASY WYVERN
	--0x64AF	DIVER DRAGON
	--0x7F4  EON DRAGON

